### PR TITLE
Improve consistency in subversion number displays

### PR DESCRIPTION
**Pull request by TWiStErRob**

### CODE REVIEW

**Comment by TWiStErRob** [comment]
@ebelinski bump

**Comment by ebelinski** [comment]
I get the desire for consistency here. Most modern versions of Android have only one API level per major Android version. When I was originally creating this website, I started with the newest Android versions and worked my way down, only later realizing I would need to a way to explain why Android 8 has levels 27 and 26, etc, so I added the green bubbles as kind of minor explanatory tidbits. But of course now I realize pretty much anything Android 8 and below has multiple API levels per major version, and now so does Android 12 too, thanks to 12L.

I think if we want to display this information for all API levels, we might as well use a separate column. Let me try something out in a separate PR...

**Comment by ebelinski** [comment]
I get the desire for consistency here. Most modern versions of Android have only one API level per major Android version. When I was originally creating this website, I started with the newest Android versions and worked my way down, only later realizing I would need to a way to explain why Android 8 has levels 27 and 26, etc, so I added the green bubbles as kind of minor explanatory tidbits. But of course now I realize pretty much anything Android 8 and below has multiple API levels per major version, and now so does Android 12 too, thanks to 12L.

I think if we want to display this information for all API levels, we might as well use a separate column. Let me try something out in a separate PR...

**Comment by ebelinski** [comment]
@TWiStErRob What do you think of my idea [here](https://github.com/ebelinski/apilevels/pull/16)?

**Comment by TWiStErRob** [comment]
Sorry, forgot about this, I wrote down my thoughts in review.

**Comment by TWiStErRob** [comment]
Superseded by #16

**Comment by TWiStErRob** [comment]
I'm going to close and delete this for now. Feel free to revive or merge #16 or not :)

**Pull request closed without merging**
