### PR TITLE
Add minSdk=14 note for AndroidX

### PR DESCRIPTION
**Pull request by TWiStErRob**
similar to Compose and Google Play

### CODE REVIEW

**Comment by TWiStErRob** [comment]
@ebelinski bump

**Comment by ebelinski** [comment]
Hey @TWiStErRob, sorry for not responding earlier. I'm a little bit conflicted about adding this information. I'm trying to strike a balance on the API levels table between providing valuable practical information on the one hand and overloading the table with too much information that may be historically interesting but not practically useful on the other hand. 

Correct me if I'm wrong, since Android development is actually not my strong suite, but it seems that the minimum SDK for AndroidX falls into the second bucket. Knowing what the minimum SDK for Jetpack Compose has a practical use, because a developer can use it to determine if they can already support Jetpack Compose, or if they need to drop support for older Android versions before they can add it. But knowing that the minimum SDK for AndroidX is 14 (Android 4 from 2011) seems to be interesting, but not that valuable information, because pretty much every app is already using level 14 or higher, and Google Play doesn't support level 18 or below anyway. Also, it seems that Google is deemphasizing "AndroidX" branding in favor of "Jetpack". 

But I dunno, on the other hand maybe there are devs in developing countries still making apps for Android 3 and 4, in which case it would be valuable information. And maybe not every developer knows that they probably don't need to bump up their minimum SDK in order to use Jetpack/AndroidX. What do you think @TWiStErRob?

**Comment by TWiStErRob** [comment]
You might be right, the reasons I think it still fits:
 * I would imagine there are enough lowly maintained legacy apps out there, who might yet to do AndroidX migration, so it might be useful info for them when they have to upgrade.
 * You have a good point about emerging markets, they might have a higher distribution of older devices.
 * Google Play Services (18) is one thing, you can write tons of apps without that, it might not be as common to use as AndroidX.
 * Interesting point about Jetpack VS AndroidX, we can change to `<a>Jetpack AndroidX</a>`, open the [url](https://developer.android.com/jetpack/androidx), the page describes what it is. This is their getting started page, and is colloquially known as AndroidX. So until Google stops mentioning it I would stick to it.
 * As I see the whole website's purpose is to show history, isn't it? We could say anything before API 31 is history.
 * This banner is below the fold on a 1080p screen, so I don't think it's much noise.

**Comment by ebelinski** [comment]
I think that reasoning makes sense, thank you. I'll merge this, and tweak the language a bit to mention Jetpack.

**Pull request merged**
